FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

USER user
ENV HOME /home/user
WORKDIR $HOME
#ENTRYPOINT ["/opt/flexget/bin/flexget"]
#CMD ["-L","debug","-l","/dev/null","daemon","start"]
