FROM ${IMAGE_PARENT}
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /
#ADD rootfs /

# User setup
USER user
ENV HOME /home/user
WORKDIR $HOME

ENTRYPOINT [ "/opt/matterbridge/matterbridge-linux-amd64" ]
CMD ['-config']
