# start the build container in privileged mode, required for glibc. use ## to comment out
#BUILD_PRIVILEGED
FROM gentoobb-arm/bob
MAINTAINER Erik Dannenberg <erik.dannenberg@bbe-consulting.de>

CMD ["/bin/bash"]
