FROM ${IMAGE_PARENT}
MAINTAINER ${MAINTAINER}

ADD rootfs.tar            /
ADD rootfs/root/.asoundrc /root/
ADD rootfs/etc/dark.cfg   /etc/
ADD rootfs/etc/ice.xml    /etc/

RUN ldconfig

#USER tor

#ENTRYPOINT [ "tor "]
#CMD [ "-f", "/etc/tor/torrc.default" ]
