FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /
ADD config /opt/logstash/config

RUN sh -c '{ DEBUG=1 JARS_SKIP="true" /opt/logstash/bin/logstash-plugin install logstash-input-rss ; }'

VOLUME /opt/logstash/config
VOLUME /opt/logstash/logs

USER logstash

ENTRYPOINT ["/opt/logstash/bin/logstash"]
CMD ["-f","/etc/logstash/rss.conf","-r"]
