FROM ${IMAGE_PARENT}
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

# We need to set it here again as direct scsynth calls does't get the startup file
#ENV SC_JACK_DEFAULT_OUTPUTS darkice:left,darkice:right,

#USER root
ENV HOME /root
ENV SC_JACK_DEFAULT_OUTPUTS darkice:left,darkice:right,
ENV LD_LIBRARY_PATH /opt/oracle-jdk-bin-1.8.0.152/jre/lib/amd64/server/:/opt/oracle-jdk-bin-1.8.0.152/jre/lib/amd64/ 

WORKDIR /overtone2

RUN ldconfig
