FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

RUN sed -i 's/daemonize yes/#daemonize yes/g' /etc/redis.conf && \
    sed -i 's/bind 127.0.0.1/#bind 127.0.0.1/g' /etc/redis.conf

ENTRYPOINT [ "/usr/sbin/redis-server" ]
CMD [ "/etc/redis.conf" ]

EXPOSE 6379
