FROM ${IMAGE_PARENT}
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /
# https://raw.githubusercontent.com/tidalcycles/Tidal/master/tidal.el
ADD rootfs /

#USER tor

#ENTRYPOINT [ "tor "]
#CMD [ "-f", "/etc/tor/torrc.default" ]
